### ISSUE TITLE
Integrar NPM

### ISSUE THREAD

**Issue by roura356a** [NeoRazorX/facturascripts_2015#16]
Sería genial si usásemos NPM en este proyecto, todo el Javascript y el CSS sería fácilmente actualizable y mantenible. Me ofrezco a portar el CSS a SCSS y todo el JS externo bajo NPM. Qué opinas? Sería abrir un nuevo branch `develop` e ir lanzando las releases a master desde ahí.

**Comment by NeoRazorX** [comment]
Ok, abre una rama y prueba. Nunca he usado npm, pero si ayuda no tengo problema.

**Comment by roura356a** [comment]
He portado todo el CSS y JS a NPM y de momento todo funciona bien en mi servidor con la instalación de prueba.

Voy a realizar unas mejoras durante estos días y luego mandaré el primer PR. Cuando puedas, por favor, crea el branch `develop` y así puedo lanzar ahí mis cambios para que les vayas echando un vistazo sin romper nada =)

**Comment by NeoRazorX** [comment]
Ya está creada.
